<?php
namespace app\controllers;

use app\models\Utils;
use yii\rest\ActiveController;

class CompaniesController extends ActiveController
{
    public $modelClass = 'app\models\Companies';

    public function beforeAction($action)
    {
        $data = \Yii::$app->getRequest()->getBodyParams();
        $data['quota'] = Utils::quotaToMB($data['quota_type'], $data['quota']);;
        \Yii::$app->getRequest()->setBodyParams($data);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}