<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "companies".
 *
 * @property integer $id
 * @property string $name
 * @property integer $quota
 */
class Companies extends \yii\db\ActiveRecord
{
    const MB = 0;
    const GB = 1;
    const TB = 2;

    public $quota_type;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'companies';
    }

    public function beforeDelete()
    {

        Users::deleteAll("company_id = :company_id", [
            "company_id" => \Yii::$app->getRequest()->get('id')
        ]);

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['quota', 'name'], 'required', 'message' => 'Поле должно быть заполнено'],
            [['quota_type'], 'integer'],
            ['quota', 'number'],
            [['name'], 'string', 'max' => 255],
            [['quota', 'name'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название компании',
            'quota' => 'Квота',
        ];
    }

    public function getAllCompanies()
    {
        return Companies::find()
            ->orderBy(['id' => SORT_ASC])
            ->asArray()
            ->all();
    }
}
